# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Random
version:      1.25
version_from: lib/Crypt/Random.pm
installdirs:  site
requires:
    Class::Loader:                 2.00
    Math::Pari:                    2.001804

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
